name: dl-challenge
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - numpy=1.23
  - scipy
  - pandas
  - matplotlib
  - pytorch=2.3.1
  - torchvision=0.18.1
  - pip
  - scikit-image
  - scikit-learn
  - jupyterlab
  - tqdm
  - pip:
    - onnxruntime
